#-----------------
# Build settings
#-----------------

markdown: kramdown
permalink: pretty
title: Jesse Zhang
description: Student // Engineer

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested


#-----------------
# Header Section
#-----------------

menu:
- {name: About Me, url: '#aboutme'}
- {name: Former Projects, url: '#projects'}
- {name: Experience, url: '#experience'}
- {name: Contact, url: '#contact'}


#-----------------
# About Section
#-----------------

bg-pic: tahoe.jpg
face-pic: face.png
blurb: <p><strong>Hi, I'm Jesse. </strong> I'm currently a first year PhD student in electrical engineering at Stanford University. What you see here is me trying to learn how to make a website. I am going to fill this space with random gibberish until I can find time to put more meaningful content. I do this to make this paragraph look longer, giving me a sense of what it will look like. More content coming soon hopefully. Purple shoelaces running down dandelions. </p>
port: 8000


#-----------------
# Projects Section
#-----------------

projects:
- {name: Swarm Bots, folder: 'proj-1'}
- {name: AM Radio Transmitter, folder: 'proj-2'}
- {name: Identifying Neurons, folder: 'proj-3'}
- {name: MTG Price Predictor, folder: 'proj-4'}
- {name: Downhill Skier Game, folder: 'proj-5'}
- {name: Active Noise Cancelling iPhone App, folder: 'proj-6'}

