#---------------------
# Build settings
#---------------------

markdown: kramdown
permalink: pretty
title: Jesse Zhang

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested

# Some colors

accent: "#c99065"
textColor: "#666"
headlineColor: "#333"
bgcolor: "#e5eaee"
documentBackgroundColor: "#fff"

#---------------------
# Header Section
#---------------------

menu:
- {name: About Me, url: '#aboutme'}
- {name: Former Projects, url: '#projects'}
- {name: Experience, url: '#experience'}
- {name: Contact, url: '#contact'}


#---------------------
# About Section
#---------------------

bg-pic: tahoe.jpg
face-pic: face.png
blurb: <p><strong>Hi, I'm Jesse. </strong> I'm currently a second year PhD student in electrical engineering at Stanford University. My interests are broad, but ultimately I hope to create something awesome that lies at the intersection of machine learning, optimization, genomics, and statistics. At the moment, I am a member of <a href="https://web.stanford.edu/~dntse/">David Tse</a>'s group, and my research revolves around analysis of single-cell RNA-Seq datasets. </p> <p>I was born in Beijing, and I grew up in the Boston area. After graduating from Newton South High School in 2010, I entered Tufts University as a biology major set on going to medical school. I'm not sure exactly what happened along the way, but somehow I ended up graduating with a degree in electrical engineering and a little extra knowledge about genetics. Outside of graduate school, I enjoy messing around on the piano, playing tennis, and going on spontaneous boba tea runs. </p>
port: 8000


#---------------------
# Projects Section
#---------------------

projects:
- {name: Swarm Bots, folder: 'proj-1'}
- {name: Transcript Compatibility Counts, folder: 'proj-2'}
- {name: Denoising single-cell dataset, folder: 'proj-3'}
- {name: Trading Card Price Predictor, folder: 'proj-4'}
- {name: Downhill Skier Game, folder: 'proj-5'}
- {name: Noise Cancelling iPhone App, folder: 'proj-6'}

#---------------------
# Experience Section
#---------------------

jobs:
- {name: MC10, logo: mc10.jpg, dates: 'May 2014 - Aug. 2014', description: '<p>MC10, inc. is a start-up that creates flexible devices for biomedical applications. As the signal processing guy in a three-person R&D intern team, I implemented machine learning and signal processing algorithms to facilitate real-time and offline accelerometer data analysis. I worked closely with the firmware team to optimize the hardware-software interface. At the end of my internship after weeks of debugging, I proudly presented an original algorithm that was selected to become the core feature of the company&#39;s first application on the market.', link: 'http://www.mc10inc.com/'}
- {name: MIT Lincoln Laboratory, dates: 'Jun. 2013 - May 2014',logo: mitll.jpg, description: '<p>During my year at MIT Lincoln Laboratory, I worked as an intern/co-op for Group 33: Advanced Sensor Systems and Test Beds. I developed MATLAB algorithms to intelligently extract traces from ionogram images generated using data collected from an over-the-horizon radar system. During the process, I created a graphical user interface in MATLAB to facilitate ionogram image processing.</p>', link: 'https://www.ll.mit.edu/'}
- {name: Tufts Biomedical Engineering Department, logo: tuftsbme.jpg, dates: 'Sep. 2011 - Aug. 2012', description: '<p>While transitioning from a biology major to an electrical engineering major, I sought a research experience that laid at the intersection of the two disciplines. During my sophomore year, I worked with Min Tang-Schomer, who at the time was a postdoc in the David Kaplan group. I designed and constructed gold circuits on silk scaffolds to control and detect neuronal signals. I then processed and analyzed the signals using pCLAMP software.</p>', link: 'http://engineering.tufts.edu/bme/kaplan/'}
- {name: Tufts Academic Resource Center, logo: tuftsarc.jpg, dates: 'Aug. 2012 - May 2014', description: '<p>During my two-year experience as a head tutor for the Tufts Academic Resource Center, I tutored introductory physics, introductory chemistry, calculus III, differential equations, and linear algebra. In addition to hosting weekly office hours and 1-on-1 sessions, I also collaborated with other tutors and professors to lead large-scale review sessions and residential events.</p>', link: 'http://uss.tufts.edu/arc/'}
- {name: Dana Farber Cancer Institute, logo: danafarber.jpg, dates: 'May 2011 - Aug. 2011', description: '<p>After my freshman year at Tufts, I worked with Hansen He, who at the time was a postdoc in the Myles Brown group at the Dana Farber Cancer Institute. Using an epigenetics approach, I conducted wet-lab experiments such as PCR, ChIP-chip, and western blotting to define role of lysine-specific demethylase 1 in human prostate cancer. The results were analyzed using Excel, python, and visualization tools at cistrome.org. I was proud to play a small role in a project that ended up being published in <a href="http://www.cell.com/cell-reports/abstract/S2211-1247(14)00962-0">Cell Reports</a>. </p>', link: 'http://research4.dfci.harvard.edu/brownlab/'}
