# Build settings

markdown: redcarpet
permalink: pretty

port: 8000

include: ['_includes/work']
exclude: ['the_design.psd','CNAME','Gemfile','Gemfile.lock']

sass:
  sass_dir: assets/css
  style: :nested