# Build settings

markdown: kramdown
permalink: pretty
title: Jesse Zhang
description: Student // Engineer

port: 8000

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested